[Feature] Retrieve fields from API results & add headers
be-ys-cloud/Genesis pull request #3
Opened 2024-06-24 13:44 UTC by RemyGomes

This pull request adds 2 features:

One allows you to retrieve values from an API using the JSON format
The other adds headers to HTTP requests. For example, to execute authenticated requests

2024-06-24 13:53 UTC, florian-forestier reviewed
LGTM :+1:

2024-06-24 13:53 UTC, florian-forestier commented on internal/services/fetch.go
> +	if len(headers) != 0 {
I think we don't need to check length as we are using a for each loop just below :smile:

2024-07-02 09:58 UTC, teapot9 requested changes

2024-07-02 09:58 UTC, teapot9 commented on README.md
> +genesis_http_request_health.status{service="serviceA",url="https://serviceA.local/health"} 0
`genesis_http_request_health.status` in examples and `genesis_http_request_field` in code ?

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +		logrus.Warningf("Error trying to request %s: %s", url, err.Error())
Is it safe to continue running the function if `http.NewRequest()` failed here?
We may run into a nil pointer dereference later.

Although it's not fatal, I would call `Errorf` rather than `Warningf`, since it's not expected to ever happen.

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +			return writer.String()
This is not an error from our side, the server just returned an erroneous body.
So, I don't think we have to return from the function right now.
I would have an `if err != nil { log } else { extractData }`.

There is nothing after, but if we ever add some code after this `if len(extract) > 0 ... {}` section (e.g. new feature) we may forget this `return` statement.

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +		extractData(&writer, service, url, body, extract, format)
We are ignoring the value returned by `extractData()`

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +func extractData(writer *bytes.Buffer, service string, url string, body []byte, extract map[string]structures.ExtractData, format string) string {
Do we need to return the `writer.String()` from this function?

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +			logrus.Warningf("Error while parsing json: %s", err.Error())
Maybe precise the URL that returned the bad JSON in the error

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +			logrus.Warningf("Can't read body: %s", "")
Maybe precise the URL that caused the error

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +					case float32:
note that `go` will not fallthrough switch cases, you may want to add a `fallthrough` statement here

2024-07-02 09:58 UTC, teapot9 commented on internal/services/fetch.go
> +					keyValue, exists := mapField.Values[value.(string)]
This will panic if `value` is not a string.
You can use `valueStr, ok := value.(string)` and check `ok` is `true` to check this separately.

2024-07-05 13:57 UTC, teapot9 requested changes

2024-07-05 13:57 UTC, teapot9 commented on internal/services/fetch.go
> +		logrus.Errorf("Error trying to request %s: %s", url, err.Error())
`err != nil` here so `req == nil`, we will dereference a `nil` pointer at line 27

2024-07-08 13:25 UTC, teapot9 commented
LGTM

2024-08-22 13:03 UTC, florian-forestier commented
Hi @teapot9 and @RemyGomes,

Thanks a lot for your work on Genesis, we deeply appreciate it. :heart:

2024-08-22 13:03 UTC, merged